"""LaTeX for the paper, generated from the pooled Q16 records.

Every number the Q16 section quotes is written as a macro, so the text and the tables are
set from the same CSVs and update together when a run is added or redone:

- ``\\retiming{model}{condition}{field}`` -- image effects (``effects.csv``). Fields:
  ``lpips`` (mean), ``lpips-ci`` (``[low, high]``), ``lpips-full`` (both), the same for
  ``clipt`` (change in CLIP image--text similarity), and ``n`` (prompt--seed pairs).
- ``\\retimingC{model}{treatment-vs-reference}{field}`` -- pre-declared paired contrasts
  (``contrasts.csv``), fields as above.
- ``\\retimingL{model}{condition}{field}`` -- the state after the natural end
  (``late_state.csv``): ``attn`` (share of all attention, percent), ``norm`` (largest
  norm over the block median), ``sinks`` (sinks elsewhere per block).
- ``\\registerP{model}{field}`` -- the register profile (``register_profile.csv``) and the
  frozen protocol: ``tokens``, ``normratio``, ``cos``, ``attn``, ``attnpertoken``,
  ``formation``, ``end``, ``blocks``, ``window``.

Models are ``flux`` (FLUX.1-dev), ``schnell`` (FLUX.1-schnell) and ``pixart``
(PixArt-Sigma); conditions are the run's keys with underscores as hyphens
(``induce-E3``, ``control-random-direction``). A missing value prints a bold ``??`` in the
PDF instead of failing the build.
"""
from __future__ import annotations

import math
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence

from .q16_main import DepthProtocol, condition_catalog

__all__ = ["MODEL_KEYS", "latex_macros", "latex_retiming_table", "write_paper_tex"]

MODEL_KEYS = {"flux1-dev": "flux", "flux1-schnell": "schnell",
              "pixart-sigma-1024": "pixart", "pixart-sigma-512": "pixartlow",
              "tiny-flux1": "tinyflux", "tiny-pixart": "tinypixart"}
MODEL_NAMES = {"flux1-dev": "FLUX.1-dev", "flux1-schnell": "FLUX.1-schnell",
               "pixart-sigma-1024": "PixArt-$\\Sigma$", "pixart-sigma-512": "PixArt-$\\Sigma$",
               "tiny-flux1": "Synthetic FLUX", "tiny-pixart": "Synthetic PixArt"}
_METRICS = {"lpips": "lpips", "clip_prompt_similarity_change": "clipt"}

_HEADER = r"""% Generated by ditsinks.q16_paper -- do not edit by hand; regenerate from the CSVs.
\makeatletter
\providecommand{\retiming}[3]{\@ifundefined{qret@#1@#2@#3}{\textbf{??}}{\@nameuse{qret@#1@#2@#3}}}
\providecommand{\retimingC}[3]{\@ifundefined{qcon@#1@#2@#3}{\textbf{??}}{\@nameuse{qcon@#1@#2@#3}}}
\providecommand{\retimingL}[3]{\@ifundefined{qlate@#1@#2@#3}{\textbf{??}}{\@nameuse{qlate@#1@#2@#3}}}
\providecommand{\registerP}[2]{\@ifundefined{qreg@#1@#2}{\textbf{??}}{\@nameuse{qreg@#1@#2}}}
"""


def _key(text: str) -> str:
    return str(text).replace("_", "-")


def _model(checkpoint: str) -> str:
    return MODEL_KEYS.get(str(checkpoint), _key(checkpoint))


def _finite(value) -> bool:
    try:
        return value is not None and math.isfinite(float(value))
    except (TypeError, ValueError):
        return False


def _fmt(value, digits: int = 3) -> str:
    if not _finite(value):
        return "n/a"
    value = float(value)
    text = f"{value:.{digits}f}"
    return "$-$" + text[1:] if text.startswith("-") else text


def _pct(value, digits: int = 1) -> str:
    return f"{100 * float(value):.{digits}f}\\%" if _finite(value) else "n/a"


def _define(lines: List[str], name: str, value: str) -> None:
    lines.append(f"\\@namedef{{{name}}}{{{value}}}")


def latex_macros(effects=None, contrasts=None, late=None, profile=None,
                 protocols: Optional[Mapping[str, DepthProtocol]] = None,
                 digits: int = 3) -> str:
    """Every Q16 number as a LaTeX macro (see the module docstring for the names)."""
    lines = [_HEADER.rstrip("\n")]
    if effects is not None and not effects.empty:
        for row in effects.itertuples():
            metric = _METRICS.get(getattr(row, "metric", ""))
            if metric is None:
                continue
            base = f"qret@{_model(row.checkpoint)}@{_key(row.condition)}@{metric}"
            ci = f"[{_fmt(row.ci_low, digits)}, {_fmt(row.ci_high, digits)}]"
            _define(lines, base, _fmt(row.mean, digits))
            _define(lines, base + "-ci", ci)
            _define(lines, base + "-full", f"{_fmt(row.mean, digits)} {ci}")
            if metric == "lpips":
                _define(lines, f"qret@{_model(row.checkpoint)}@{_key(row.condition)}@n",
                        str(int(row.n_units)))
    if contrasts is not None and not contrasts.empty:
        for row in contrasts.itertuples():
            metric = _METRICS.get(getattr(row, "metric", ""))
            if metric is None:
                continue
            base = (f"qcon@{_model(row.checkpoint)}@{_key(row.treatment)}-vs-"
                    f"{_key(row.reference)}@{metric}")
            ci = f"[{_fmt(row.ci_low, digits)}, {_fmt(row.ci_high, digits)}]"
            _define(lines, base, _fmt(row.difference, digits))
            _define(lines, base + "-ci", ci)
            _define(lines, base + "-full", f"{_fmt(row.difference, digits)} {ci}")
    if late is not None and not late.empty:
        for row in late.itertuples():
            base = f"qlate@{_model(row.checkpoint)}@{_key(row.condition)}"
            _define(lines, base + "@attn", _pct(row.attention_share_after_end))
            _define(lines, base + "@norm", _fmt(row.norm_ratio_after_end, 1))
            _define(lines, base + "@sinks", _fmt(row.new_sinks_after_end, 1))
    if profile is not None and not profile.empty:
        for row in profile.itertuples():
            base = f"qreg@{_model(row.checkpoint)}"
            values = {"tokens": _fmt(getattr(row, "register_tokens", None), 0),
                      "normratio": _fmt(getattr(row, "register_norm_over_median", None), 1),
                      "cos": _fmt(getattr(row, "register_cosine", None), 3),
                      "attn": _pct(getattr(row, "attention_share_to_register", None)),
                      "attnpertoken": _pct(getattr(row, "attention_share_per_register_token",
                                                   None), 2)}
            for field, value in values.items():
                _define(lines, f"{base}@{field}", value)
    for checkpoint, p in (protocols or {}).items():
        base = f"qreg@{_model(checkpoint)}"
        _define(lines, f"{base}@formation", str(int(p.formation)))
        _define(lines, f"{base}@end", str(int(p.natural_end)))
        _define(lines, f"{base}@blocks", str(int(p.n_layers)))
        _define(lines, f"{base}@window", str(int(p.window_length)))
        for name, (a, b) in p.windows.items():
            _define(lines, f"{base}@blocks-{_key(name)}", f"{int(a)}--{int(b)}")
    lines.append("\\makeatother")
    return "\n".join(lines) + "\n"


# Rows of the retiming table: (group heading, condition key or template, row label).
def _rows(protocol: DepthProtocol) -> List[tuple]:
    rows = []
    for i, w in enumerate(protocol.early_windows()):
        rows.append(("Before formation", f"induce_{w}", f"Induced, window E{i + 1}"))
    if "N" in protocol.windows:
        rows.append(("At the natural depth", "induce_N", "Rewritten in place"))
    for i, w in enumerate(protocol.late_windows()):
        rows.append(("After the natural end", f"induce_{w}", f"Induced, window L{i + 1}"))
    rows.append(("After the natural end", "extend", "Maintained past the end"))
    rows.append(("Removal", "remove", "Natural register removed"))
    if protocol.primary_early:
        rows.append(("Removal", f"remove_induce_{protocol.primary_early}",
                     "Removed; induced before formation"))
    if protocol.primary_late:
        rows.append(("Removal", f"remove_induce_{protocol.primary_late}",
                     "Removed; induced after the end"))
    rows += [("Controls (blocks of E3)", "control_random_direction",
              "Random direction, norm-matched"),
             ("Controls (blocks of E3)", "control_ordinary_positions",
              "Same state, non-register positions"),
             ("Controls (blocks of E3)", "control_in_distribution",
              "$v^\\star$ at in-distribution strength")]
    return rows


def _range(a, b) -> str:
    return f"{int(a)}--{int(b)}" if int(a) != int(b) else f"{int(a)}"


def _span(protocol: DepthProtocol, condition: str) -> str:
    """The blocks a condition edits; a removal plus induction lists both."""
    catalog = {c.key: c for c in condition_catalog(protocol)}
    c = catalog.get(condition)
    removal = protocol.removal_window()
    if c is None:
        return "--"
    parts = [_range(removal.first, removal.last)] if c.remove else []
    if c.window and c.window in protocol.windows:
        parts.append(_range(*protocol.windows[c.window]))
    return ", ".join(parts) if parts else "--"


def latex_retiming_table(effects, protocols: Mapping[str, DepthProtocol], late=None, *,
                         checkpoints: Optional[Sequence[str]] = None,
                         label: str = "tab:retiming") -> str:
    """The retiming table: per model, the blocks each condition edits, LPIPS to the
    unmodified image (mean and 95% prompt-clustered interval) and the share of all
    attention the edited positions receive after the natural end."""
    order = ["flux1-dev", "flux1-schnell", "pixart-sigma-1024", "pixart-sigma-512",
             "tiny-flux1", "tiny-pixart"]
    models = list(checkpoints or sorted(protocols, key=lambda m: order.index(m)
                                        if m in order else len(order)))
    lp = {}
    if effects is not None and not effects.empty:
        for row in effects[effects["metric"] == "lpips"].itertuples():
            lp[(row.checkpoint, row.condition)] = (row.mean, row.ci_low, row.ci_high,
                                                   row.n_units)
    attn = {}
    if late is not None and not late.empty:
        for row in late.itertuples():
            attn[(row.checkpoint, row.condition)] = row.attention_share_after_end
    n_units = {m: max([v[3] for (c, _), v in lp.items() if c == m] or [0]) for m in models}
    cols = "l" + "rrr" * len(models)
    head_models = " & ".join(f"\\multicolumn{{3}}{{c}}{{{MODEL_NAMES.get(m, m)} "
                             f"($n={int(n_units[m])}$)}}" for m in models)
    rules = " ".join(f"\\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(models)))
    sub = " & ".join("Blocks & LPIPS $\\downarrow$ [95\\% CI] & Attn.\\ after end"
                     for _ in models)
    lines = ["% Generated by ditsinks.q16_paper.latex_retiming_table -- requires booktabs.",
             "\\begin{table}[t]", "\\centering", "\\small",
             "\\setlength{\\tabcolsep}{4pt}",
             "\\resizebox{\\linewidth}{!}{%",
             f"\\begin{{tabular}}{{{cols}}}", "\\toprule",
             f" & {head_models} \\\\", rules, f"Condition & {sub} \\\\", "\\midrule"]
    reference = protocols[models[0]]
    group = None
    for heading, condition, text in _rows(reference):
        if heading != group:
            if group is not None:
                lines.append("\\addlinespace[2pt]")
            lines.append(f"\\multicolumn{{{1 + 3 * len(models)}}}{{l}}{{\\emph{{{heading}}}}} \\\\")
            group = heading
        cells = []
        for m in models:
            p = protocols[m]
            value = lp.get((m, condition))
            estimate = ("--" if value is None else
                        f"{_fmt(value[0])} [{_fmt(value[1])}, {_fmt(value[2])}]")
            share = attn.get((m, condition))
            cells += [_span(p, condition), estimate, _pct(share) if share is not None else "--"]
        lines.append(f"\\quad {text} & " + " & ".join(cells) + " \\\\")
    ref_share = " / ".join(f"{MODEL_NAMES.get(m, m)} {_pct(attn[(m, 'reference')])}"
                           for m in models if (m, "reference") in attn)
    lines += ["\\bottomrule", "\\end{tabular}}",
              "\\caption{Retiming the register state. For each model, the blocks an edit "
              "covers, the LPIPS between the edited and the unmodified image of the same "
              "prompt, seed and initial noise (mean over prompt--seed pairs; 95\\% bootstrap "
              "interval resampling prompts), and the share of all attention the edited "
              "positions receive after the natural end of the register (readout step; "
              "median over pairs"
              + (f"; unmodified: {ref_share}" if ref_share else "") + "). Every edit is "
              "applied over the first third of the denoising steps, to every pass of the "
              "sampler.}",
              f"\\label{{{label}}}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def write_paper_tex(out_dir, *, effects=None, contrasts=None, late=None, profile=None,
                    protocols: Optional[Mapping[str, DepthProtocol]] = None) -> Dict[str, Any]:
    """Write ``q16_numbers.tex`` (macros) and ``table_retiming.tex`` into ``out_dir``."""
    from pathlib import Path

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written = {}
    (out / "q16_numbers.tex").write_text(latex_macros(effects, contrasts, late, profile,
                                                      protocols))
    written["macros"] = out / "q16_numbers.tex"
    if protocols:
        (out / "table_retiming.tex").write_text(latex_retiming_table(effects, protocols, late))
        written["table"] = out / "table_retiming.tex"
    return written
